### ISSUE TITLE
The GitHub actions build runner fails on PRs

### ISSUE THREAD

**Issue by Olf0** [CepiPerez/filecase-sailfish#16]
@ruditimmer, the GitHub actions build runner you implemented so nicely fails on Pull Requests (PRs), while it works fine once a PR has been merged (i.e., on exactly the same code).
This pattern has become obvious throughout the last couple of PRs, see https://github.com/CepiPerez/filecase-sailfish/actions

Because it is a irritating when a correct PR fails and this counteracts the very purpose of a build pipeline (do detect build errors early), I would appreciate very much if you fix that, so the "build runner runs properly" / the "build workflow flows nicely". :wink:

Thank you!

**Comment by ruditimmer** [comment]
I have made a PR to see if it would be fixed now. let's see

**Comment by Olf0** [comment]
> I have made a PR to see if it would be fixed now. let's see

For reference: That is PR #18.

**Comment by ruditimmer** [comment]
For now it works i need only to look to upload the build to release would do that tomorow.

**Comment by Olf0** [comment]
@ruditimmer, as a side note: The is something severely wrong with your git workflow.  You are repeatedly pushing commits which were already merged, which completely messes up the commit history and will make reverting commits and "cherry picking" commits (between branches) hard to logistically impossible:
1. You PR #20 contains two older, already merged commit from me, see [[1a]](https://github.com/CepiPerez/filecase-sailfish/pull/20/commits/e5df8865a892ca17272d2a75e1fa88c0b2326a68#diff-91cbf11fb1958c047c46ddb91ba505b284cbd428455c3ba076cf4ab1f4952918) and [[2a]](https://github.com/CepiPerez/filecase-sailfish/pull/20/commits/e5df8865a892ca17272d2a75e1fa88c0b2326a68#diff-6b2f0a449fdefd8930e23ef0dcd752beec69242e1303d77653f047c5e0766385).
   These were originally merged by Matias in [[1]](https://github.com/CepiPerez/filecase-sailfish/pull/17/files) and [[2]](https://github.com/CepiPerez/filecase-sailfish/pull/14/files).
2. You seem to be re-merging your own commits again, resulting in PRs with no changes, but doubly added commits. See e.g. [PR 22](https://github.com/CepiPerez/filecase-sailfish/pull/22/files), which has no changes, but [two commits](https://github.com/CepiPerez/filecase-sailfish/pull/22/commits).  Obviously they were already there.
   In a way this is the opposite of point 1, where you re-committed my already merged commits as yours.  I wonder how to achieve that without additional changes, but this must be avoided.
3. Please squash-merge your commits when merging a PR.
4. Please test your changes in *your own* repository before merging first and then fixing it multiple times.  You should have sufficient reason to assume that your changes are working, *before* committing them upstream.
5. Please use descriptive commit comments, i.e., more than just "Fix"!

My suggestion is to use the GitHub web-frontend for handling this upstream repository.  Then you can let your local repository (on your computer) and your repository at GitHub interact in any way you like.  But only create PRs and push them into this upstream repository from your own GitHub repository, when they are really ready.  Plus use the GH-webfrontend for this, because it is quite fail-safe.

@CepiPerez, while I accepted your invitation as a contributor, I do think it is a bad idea to let three different people with vastly different styles of managing a repository directly commit into your upstream repository.   Three people do not automatically form a team, if there is no coherence between them.
At least there should be a compulsory review of another contributor (for quality assurance), which an be configured in the GH repository setting.
But ultimately you should ask yourself what you want to achieve?  I already suggested to meet a clear decision, if you want to be the maintainer and responsible (but then you shall be the reviewer and handle this responsibly), or if you want to get rid of this workload: Then you shall archive all six of your repositories (which is revert-able).  See [details how to achieve that here](https://github.com/sailfishos-chum/main/issues/66#issuecomment-1037553147).

**Comment by ruditimmer** [comment]
Hi Olf,

Oh that's indeed bad sorry i dont see that is happend !

Ok i quit with it again sorry for that i'm not good with git stuff i use SmartGit here so it should be that software what is doing wrong. again sorry for that. I try it on my own repo but it seems Smartgit was doing something strange indeed. About description i indeed add a more explaine description but as told it seems SmartGit messed it up into some way.

So i will not commit anymore and close the case here. And will remove myself from the repo also as managing it directly.

**Comment by Olf0** [comment]
> Oh that's indeed bad sorry i dont see that is happend !

Well, shit happens.
The crucial point always is how to handle that.

> Ok i quit with it again sorry for that i'm not good with git stuff i use SmartGit here so it should be that software what is doing wrong. again sorry for that. I try it on my own repo but it seems Smartgit was doing something strange indeed.

Hey Rudi, no reason to give up that quickly.  And I did not mean to be overly harsh, I just intended to concisely name the issues I perceived.

I tried to show you a way to avoid such mishaps: Prepare and test everything at your own GitHub repository.  When it is really ready and working, then solely use the GitHub web-frontend to create Pull Requests from your to this repository.
The GitHub web-frontend is really nice, easy and fail-safe.

> About description i indeed add a more explaine description

Yes, that would be nice in order to understand what was altered without having to read the source code changes in detail.

> So i will not commit anymore and close the case here. And will remove myself from the repo also as managing it directly.

Please do not do that.  Both!
If Cepi switches on mandatory reviews as I suggested, then three people is the minimal number for that to work well in practice.

**Comment by ruditimmermans** [comment]
Hi Olf0,

The build script is now fixed i have done a lot a of testing on my repo before i do a merge request.
I fix also the SD-Card show now it show this before it was broke.

Greetings,
Rudi

**Comment by Olf0** [comment]
Hello Rudi, nice to hear from you.

Thank you very much for your contributions, especially switching to the build infrastructure by CODeRUS for the GitHub-actions runs here.  This looks much better (i.e., clearer & cleaner) and easier to maintain now.
Actually I considered dropping the GitHub-actions based builds, because I tried to trigger [handling FileCase as an "abandoned app" at SailfishOS:Chum](https://github.com/sailfishos-chum/main/issues/66) (so it is build there) and the original build framework did not appear to be in a good shape.  But it is much nicer to have a first build check in one's own repository, I trust coderus' build infrastructure, and currently there also is no progress at SailfishOS:Chum.

I will reviewed your Pull Requests #23 and made some small changes; thank you for leaving "allow commits from maintainers" on, so I was able to do that.  For details, see my notes there.

A single general remark: Please try to pose on PR per topic.  Taking PR #23 as an example, PR #24 would have belong to/in it (I already added that before reviewing #24), but commits [0ed2aaa](https://github.com/CepiPerez/filecase-sailfish/pull/23/commits/0ed2aaadb148f5e687c0df8593de775e7c59095d), [572e3ef](https://github.com/CepiPerez/filecase-sailfish/pull/23/commits/572e3efc1228e3166bffa1462bbb2133c661105d), [5d2f25b](https://github.com/CepiPerez/filecase-sailfish/pull/23/commits/5d2f25b2987992f14cbf3678ad50fde096be4335), [9c693fe](https://github.com/CepiPerez/filecase-sailfish/pull/23/commits/9c693fe20de02d456559fcba970bbdf61180aa86), [3c35644](https://github.com/CepiPerez/filecase-sailfish/pull/23/commits/3c356446ac40e559c7a3aa258b074e9e77d7ffc0), [aa1e173](https://github.com/CepiPerez/filecase-sailfish/pull/23/commits/aa1e1736f15b36f180de576ec6820aed5fc3c5f5) plus my commit [5e084f2](https://github.com/CepiPerez/filecase-sailfish/pull/23/commits/5e084f2aa84c309d01b3c2bea24f91dab5bdd4d9) should have been placed into a separate PR "Fix show SD-Card".
Never mind, this is O.K. for now, and I also regularly forget to clearly separate different topics into different PRs.

**Comment by Olf0** [comment]
Well, PR #23 did not fix anything.  The PRs #6, #8, #18, #19, #20, #22 and #23, which all deal with establishing a working, GH-actions based build runner seem to be written in a trial-and-error approach without having understood the documentation and examples.

It took me a couple of hours yesterday to read the documentation and examples, plus to test a few things, in order to get the build runner properly working on every created tag or commit and to identify the unrelated files, which were added in the belief to "heal" the build process.  This resulted in PR #25.
